config/routes.rb
Bloodbikeswales::Application.routes.draw do
# splash pages
  root 'splash#index'

  get 'about', to: 'splash#about', as: :splash_about
  get 'news', to: 'stories#index', as: :splash_news
  get 'events', to: 'splash#events', as: :splash_events
  get 'sponsors', to: 'splash#sponsors', as: :splash_sponsors
  get 'contact_list', to: 'splash#contact', as: :splash_contact
  get 'links', to: 'splash#links', as: :splash_links
  get 'fundraising', to: 'splash#fundraising', as: :splash_fundraising

  post 'user/:user_id/avatar', to: 'images#create', as: :user_avatar_create
#  post 'story/:story_id/image', to: 'images#story_create', as: :story_image_create


  resources :users, except: :index do
    resources :notifications, only: :index
  end

  resources :recitals
  resources :events
  resources :images

  resources :forums do
    resources :discussions do
      member do
        get 'followers', to: 'discussions#show_followers', as: :show_followers
        get 'create_follower', to: 'discussions#create_follower', as: :create_follower
        get 'delete_follower', to: 'discussions#delete_follower', as: :delete_follower
      end

      resources :replies
    end
  end

  resources :stories, except: [:edit]

  scope path: 'control_panel' do
      get 'pages', to: 'panels#pages', as: :panel_show_pages
      get 'pages/:id', to: 'panels#pages', as: :panel_edit_pages

      get 'edit_story/:id', to: 'stories#edit', as: :edit_story
      get 'stories', to: 'panels#stories', as: :panel_show_stories

      get 'users', to: 'panels#users', as: :panel_show_users
      delete 'user/:id', to: 'panels#user_delete', as: :delete_user
      patch 'user/:id', to: 'panels#user_update', as: :panel_update_user

      get 'media', to: 'panels#media', as: :panel_show_media

      get 'edit_media/:id', to: 'panels#media_edit', as: :panel_edit_media
      delete 'media/:id', to: 'panels#media_delete', as: :panel_delete_media
      patch 'media/:id', to: 'panels#media_update', as: :panel_update_media

      get 'events/:id', to: 'panels#edit_event', as: :panel_edit_event
    #  delete 'events/:id'
      
    resources :stories
  end

#  resources :stories

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user

#  get 'panels/stories', to: 'panels#stories', as: :panel_show_stories
 # delete 'panels/story/:id', to: 'panels#story_delete', as: :delete_story
 # patch 'panels/story/:id', to: 'panels#story_update', as: :panel_update_story

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user


  # use a member route here
  post 'create', to: 'create_reply/:forum_id/:discourse_id', to: 'replies#create'
  post 'create_retort/:forum_id/:discourse_id/:reply_id', to: 'retorts#create', as: :create_reply_retort

  private_dir = 'private'
  get "#{private_dir}/:file_name.:extension", to: 'images#show', as: :private_image

  get 'members_contact_list', to: 'contact_lists#show'

  get 'send_registration_email/:id', to: 'users#send_registration_email', as: :send_registration_email
  get 'culminate/:register_key', to: 'users#culminate', as: :culminate

  get 'signup', to: 'users#new', as: 'sign_up'
  get 'signin', to: 'sessions#new', as: 'sign_in'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'signout', to: 'sessions#destroy', as: 'sign_out'
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
	
	belongs_to :user
	belongs_to :forum

	has_many :replies

	has_many :followers
	has_many :users, -> { uniq }, through: :followers 

	has_many :impressions

	
	validates :name, presence: true
	validates :description, presence: true

	after_create { 
				   set_counters_to_zero 
				   add_follower(self.user)
				   iterate_forum_discussion_count 
				   set_as_last_discussion
				}

	def set_as_last_discussion
		self.forum.update_attributes(last_discussion_id: self.id)
	end


	def iterate_forum_discussion_count
		self.forum.update_attributes( discussion_count: self.forum.discussion_count + 1 )
	end

	def set_counters_to_zero
		self.view_count = 0
		self.reply_count = 0
		self.follower_count = 0
	end
	
	def iterate_reply_count
		self.update_attributes(reply_count: reply_count + 1 )

		# de iterate
	end

	def iterate_follower_count
		self.update_attributes(follower_count: reply_count + 1 )

#		self.update_attributes(follower_count: 1)
	end

#	def user_seen_me_or_owner?(user)
#		!self.impressions.exists?(ip_address: ip_address, user_id: user.id) || user.id == op.id	
#	end


	def iterate_view(ip_address, user)

		unless self.impressions.exists?(ip_address: ip_address, user_id: user.id) || user.id == op.id
				
			self.transaction do 
				self.update_attributes(view_count: view_count + 1 )
				self.impressions.create(ip_address: ip_address, user_id: user.id) 
			end

		end

	end

	def notify_all_users(reply, discussion, forum)
		self.users.each do |user|


#			DiscussionMailer.delay.new_reply_notification(user, reply, discussion, forum ) unless reply.user == user #.deliver 

			#unless follower.is_current_user?
		end
	end


	def last_reply
		self.replies.last
	end

	# alias_method :op, :user
	def op
		self.user
	end

	def add_follower(user)

	
		unless self.followers.exists?(user_id: user.id)

			self.transaction do
				self.update_attributes(follower_count: follower_count + 1)
				self.followers.create(user_id: user.id)
			end
			
		end


	end

	def delete_follower(user)

	
		if self.followers.exists?(user_id: user.id)

			self.transaction do
				self.update_attributes(follower_count: follower_count - 1)
					


				user = self.followers.find_by(user_id: user.id)

				ap user

				user.delete
			end
			
		end


	end

	alias_method :author, :user

	def author_exists?
		author.present?
	end

	def author_name
		author_exists? ? user.user_name : super
	end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_forum, only: [:create, :show, :show_followers, :create_follower, :delete_follower]
  before_action :create_reply, only: [:show]

  before_action :set_discussion, only: [:show, :show_followers, :create_follower, :delete_follower]
  
  before_action :no_guests
  
  before_action :check_role
  def show
    @discussion.iterate_view(request.remote_ip, current_user)
    @replies = @discussion.replies.paginate(page: params[:page], per_page: 10)
  end

  def create  
    @discussion = @forum.discussions.new(discussion_params)
    @discussion.user_id = current_user.id
     
    if @discussion.save
    
      redirect_to forum_path(@forum), notice: 'discussion successfully created!'
    else

      @discussions = Discussion.where(forum_id: @forum)
      @discussions = @forum.discussions.paginate(page: params[:page], per_page: 10, order: 'created_at desc')

      flash.now[:notice] = 'Discussion could not be saved' 
      render "forums/show" #forum_path(@forum), notice: 'sorry, your discussion could not be saved!'
    end    
  end

  def show_followers
    @followers = @discussion.followers
  end

  def create_follower
    @discussion.add_follower(current_user)
    redirect_to forum_discussion_url(@discussion.forum, @discussion), notice: "You are now following #{@discussion.name}"
  end

  def delete_follower
    @discussion.delete_follower(current_user)
    redirect_to forum_discussion_url(@discussion.forum, @discussion), notice: "You are no longer following #{@discussion.name}"
  end

  def update
  #  @discussion.update(discussion_params)

  #  ap 'hmmm'

#    redirect_to forum_path(@forum)
  end



  private
    
    def check_role
     
      unless @forum.user_allowed?(current_user) || current_user.is_admin?
        redirect_to forums_path, notice: 'Sorry! You cannot enter this discussion! This forum is for users with a type of: ' + @forum.list_roles + ' and your roles are: ' + current_user.list_roles
      end

    end

    def create_reply
      @reply = Reply.new  
    end

    def set_forum
      @forum = Forum.find(params[:forum_id]).decorate
    end

    def set_discussion
      @discussion = Discussion.find(params[:id]).decorate
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:name, :description)
    end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_form.html.erb
<%= form_for( [@forum, @discourse] ) do |f| %>
 

  <% if @discourse.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@discourse.errors.count, "error") %> prohibited this discourse from being saved:</h2>

      <ul>
      <% @discourse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">



    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
  

    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discussions/_reply.html.erb
<div class = 'post'>
  
    <div class="commentbox">
        

        <%= link_to reply.user do %>
          <%= show_uploaded_image(reply.user.avatar, class: 'mugshot',  width: 37, height: 45, width: 50, height: 50 ) %>

        <% end %>
      
	         
          <p> <%= link_to reply.user.user_name, reply.user %> <%= @discussion.user.list_roles %> </p>
	        <p> <%= reply.description %> </p>
	        
    
        <p><i class="fa fa-comment"></i> <%= time_ago_in_words(reply.created_at) %> ago </p>
         <p>&nbsp;</p>


    </div>



  <p><%#= render partial: 'reply', collection: reply.retorts %></p>

</div>

app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Forum</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
   
  </tbody>
</table>

<br>
----------------------


 <% if !@discussion %>
  No discussions!
 <% else %>
   <% @discussion.each do |discussion| %>
        <tr>
          <td><%= discussion.name %></td>
          <td><%= discussion.forum_id %></td>
          <td><%= link_to 'Show', discussion %></td>
          <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
          <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  <% end %>

<%#= link_to 'New Discussion', new_discussion_path %>

app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

app/views/discussions/show.html.erb
<div class="fullwidthcontainer">
  

  <div class="container">

<div class="row">
<div class="col-md-12">
      
  
        <h2><%= @forum.name %></h2>
              <p>&nbsp;</p>

        <%= link_to @discussion.user do %>
          <%= show_uploaded_image @discussion.user.avatar, class: 'mugshot', width: 50, height: 50 %>
        <% end %>
        
      
        <h4> <%= @discussion.name %> </h4>
        <p> <%= @discussion.user.user_name %> <%= @discussion.user.list_roles %> </p>
        <p> <%= @discussion.description %> </p>


        

        <p><i class="fa fa-comment"></i> This discussion was created <%= time_ago_in_words(@discussion.created_at) %> ago </p>
        <p><i class="fa fa-compass"></i> <%= link_to((pluralize @discussion.follower_count, 'users'), show_followers_forum_discussion_path(@forum, @discussion) ) %> are following this discussion. <%= @discussion.decorate_follow_message %> </p>
        <p><i class="fa fa-eye"></i> <%= "#{@discussion.view_count} users have seen this discussion" %> </p>

        <p>&nbsp;</p>

        <%= form_for( @reply, url: "/forums/" + @forum.id.to_s + "/discussions/" + @discussion.id.to_s + "/replies" ) do |f| %>        
     
          <%= f.text_area :description, placeholder: 'Enter your reply here', class: 'form-control', rows: 5 %> <br>
          
          <%= f.submit "Reply to #{@discussion.user.user_name}\'s Discussion", class: 'btn btn-success' %> <br>
            <br>
        <% end %>

    
</div>
</div>
</div>

<%= will_paginate @replies %>


<div class="postdivider">
<div class="container"><h4> <%= pluralize @discussion.reply_count, 'reply' %> </h4></div>

</div>
<div class="container">
<div class="row">
<div class="col-md-12">
<p>&nbsp;</p>


        

  <%= render partial: 'reply', collection: @replies %>

<%= will_paginate @replies %>






</div>
</div>
</div>
<p>&nbsp;</p>
</div>

app/views/discussions/show_followers.html.erb
<p id="notice"><%= notice %></p>

<div class="fullwidthcontainer">
  

  <div class="container">

<div class="row">
<div class="col-md-12">
    
    

    <h3> Who's watching <%= link_to "#{@discussion.user.user_name}'s", @discussion.user %> discussion: "<%= @discussion.name %>" </h3>

    
<table class="table">
  <thead>   
      <tr>
        <td> User Name</td>

      </tr>
  </thead>
  

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
          <td> <%= link_to "#{follower.user.user_name} #{@discussion.decorate_follower_information(follower.user)}", follower.user.decorate %> </td>         
          <td> 

            <%#= helper_follow(current_user)%>
            <%#= button_to "#{follower.user.decorate.decorate_cheese(@discussion)}", root_url, class: 'btn btn-success btn-xs fleft' %>
          </td> 
      </tr> 
      

  <% end %>

        
    
  </tbody>
</table>



</div>
</div>
</div>
<div class="postdivider">

</div>
<div class="container">
<div class="row">
<div class="col-md-12">
<p>&nbsp;</p>








</div>
</div>
</div>
<p>&nbsp;</p>
</div>