config/routes.rb
Bloodbikeswales::Application.routes.draw do
# splash pages
  root 'splash#index'

  get 'about', to: 'splash#about', as: :splash_about
  get 'news', to: 'stories#index', as: :splash_news
  get 'events', to: 'splash#events', as: :splash_events
  get 'sponsors', to: 'splash#sponsors', as: :splash_sponsors
  get 'contact_list', to: 'splash#contact', as: :splash_contact
  get 'links', to: 'splash#links', as: :splash_links
  get 'fundraising', to: 'splash#fundraising', as: :splash_fundraising

  post 'user/:user_id/avatar', to: 'images#create', as: :user_avatar_create
#  post 'story/:story_id/image', to: 'images#story_create', as: :story_image_create


  resources :users, except: :index do
    resources :notifications, only: :index
  end

  resources :recitals
  resources :events
  resources :images

  resources :forums do
    resources :discussions do
      member do
        get 'followers', to: 'discussions#show_followers', as: :show_followers
        get 'create_follower', to: 'discussions#create_follower', as: :create_follower
        get 'delete_follower', to: 'discussions#delete_follower', as: :delete_follower
      end

      resources :replies
    end
  end

  resources :stories, except: [:edit]

  scope path: 'control_panel' do
      get 'pages', to: 'panels#pages', as: :panel_show_pages
      get 'pages/:id', to: 'panels#pages', as: :panel_edit_pages

      get 'edit_story/:id', to: 'stories#edit', as: :edit_story
      get 'stories', to: 'panels#stories', as: :panel_show_stories

      get 'users', to: 'panels#users', as: :panel_show_users
      delete 'user/:id', to: 'panels#user_delete', as: :delete_user
      patch 'user/:id', to: 'panels#user_update', as: :panel_update_user

      get 'media', to: 'panels#media', as: :panel_show_media

      get 'edit_media/:id', to: 'panels#media_edit', as: :panel_edit_media
      delete 'media/:id', to: 'panels#media_delete', as: :panel_delete_media
      patch 'media/:id', to: 'panels#media_update', as: :panel_update_media

      get 'events/:id', to: 'panels#edit_event', as: :panel_edit_event
    #  delete 'events/:id'
      
    resources :stories
  end

#  resources :stories

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user

#  get 'panels/stories', to: 'panels#stories', as: :panel_show_stories
 # delete 'panels/story/:id', to: 'panels#story_delete', as: :delete_story
 # patch 'panels/story/:id', to: 'panels#story_update', as: :panel_update_story

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user


  # use a member route here
  post 'create', to: 'create_reply/:forum_id/:discourse_id', to: 'replies#create'
  post 'create_retort/:forum_id/:discourse_id/:reply_id', to: 'retorts#create', as: :create_reply_retort

  private_dir = 'private'
  get "#{private_dir}/:file_name.:extension", to: 'images#show', as: :private_image

  get 'members_contact_list', to: 'contact_lists#show'

  get 'send_registration_email/:id', to: 'users#send_registration_email', as: :send_registration_email
  get 'culminate/:register_key', to: 'users#culminate', as: :culminate

  get 'signup', to: 'users#new', as: 'sign_up'
  get 'signin', to: 'sessions#new', as: 'sign_in'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'signout', to: 'sessions#destroy', as: 'sign_out'
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :secure
  
  before_action :set_all_users, only: [:user_delete, :users]
  before_action :set_all_users, only: [:stories, :users]

  before_action :set_all_stories, only: [:stories]

  before_action :set_user, only: [:user_delete, :user_update]
  before_action :protect_admin, only: [:user_delete, :user_update]
  
  def users
  end

  def user_delete
      
     
     
       @user.destroy
       respond_to do |format|
          format.html { redirect_to panel_show_users_url, notice: 'User successfully deleted' }
          format.json { head :no_content }
        end

  end


  def user_update

    flash_message = 'User <b>' + @user.user_name + '</b> was successfully altered: </br>'

    changed = false

    user_params.each do |p|
      
      if p[1] == "1" && !@user.has_role?(p[0])
        @user.add_role(p[0])

        flash_message << p[0] + ' added </br>'
        
        changed = true
      end

      if p[1] == "0" && @user.has_role?(p[0])
        @user.remove_role(p[0])  

        flash_message << p[0] + ' removed <br>'
        
        changed = true
      end


    end 

    flash_message = '' << '<b>' + @user.user_name + '\'s</b> roles have not been changed as your update doesn\'t change their already existing roles! </br>' unless changed

    flash_message << '<b>' + @user.user_name + '\'s</b> roles are currently: ' + @user.list_roles 

   redirect_to panel_show_users_url, notice: flash_message.html_safe

  end


  def stories
  end

  def pages
    @pages = Page.all
  end

  def edit_story

  end

  def media
  end

  def asd
  end

  def media_update
    
    ap params

    @field = Field.find(params[:id])
=begin
respond_to do |format|
      if @reservation.save
        format.html do
          redirect_to '/'
        end
        format.json { render json: @reservation.to_json }
        else
        format.html { render 'new'} ## Specify the format in which you are rendering "new" page
        format.json { render json: @reservation.errors } ## You might want to specify a json format as well
        end
      end
     end
=end
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to panel_show_pages_url, notice: "#{@field.name} was successfully updated." }
  #      format.json { head :no_content }
      else
        format.html { render action: 'edit' }
   #     format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  #  @field = Field.find(field_params)

  #  if @field.update(field_params)
  #    redirect_to panel_show_field_url, notice: "Updated #{@field.name}"
  #  else
  #    redirect_to panel_show_field_url, notice: "Could not update #{@field.name}"
  #  end
  end

  def media_edit
    @field = Field.find(params[:id])
    #render 'panels/media_edit'
  end


  def edit_event
  end

  def update_event
  end


  private
    
    def protect_admin
      redirect_to(panel_show_users_url, notice: 'You lack the privileges needed to alter an admin') if @user.is_admin? 
    end

    def set_all_stories
      @stories = Story.all.paginate(page: params[:page], per_page: 10).decorate
    end

    def set_all_users
     @users = User.all.paginate(page: params[:page], per_page: 10)
    end

    def secure
      redirect_to root_url if !current_user.is_admin?
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
     params.require(:user).permit(:coordinator, :midweek, :rider)
    end

    def field_params
      params.require(:field).permit(:content)
    end

    def story_params
      ap params
      params.require(:story).permit(:stuff)
    end
end

app/views/panels/_field.html.erb
<tr>
	<td> <%= field.name %> </td>
	<td> <%= field.content.truncate(100) %></td>
	<td> <%= field.last_updated_by %></td>
	<td> <%= button_to 'update', panel_edit_media_path(field), class: 'btn btn-success btn-xs form-control', method: :get %> </td>

<%#= button_to 'update', panel_edit_media_path(field), class: 'btn btn-success btn-xs', method: :get %>

</tr>

app/views/panels/_page.html.erb
<h3> <%= page.name %> </h3> 

<table class="table">
        <thead>
          <tr>
            <th>Field Description</th>
            <th>Content</th>
            <th>Last Updated By</th>
            <th></th>
          </tr>
        </thead>
        <tbody>

          <%= render partial: 'field', collection: page.fields %>

        </tbody>


	
</table>

app/views/panels/_sidebar.html.erb
</div>

<div class="row">
<div class="col-sm-2 controlsidebar">
		
<p><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> STATISTICS</a></p>
<p><a href="#"><i class="fa fa-comments fa-fw"></i> FORUM</a></p>

<!-- panel_edit_event -->

<p> <%= link_to panel_edit_event_path(1) do %> <i class="fa fa-calendar fa-fw"></i> CALENDAR <% end %> </p>
<p> <%= link_to panel_show_stories_path do %> <i class="fa fa-bullhorn fa-fw"></i> NEWS <% end %> </p>
<p> <%= link_to panel_show_pages_path do %> <i class = "fa fa-file fa-fw"></i> PAGES <% end %> </p>
<p><a href="#"><i class="fa fa-gift fa-fw"></i> DONATIONS</a></p>
<p><a href="#"><i class="fa fa-camera-retro fa-fw"></i> MEDIA</a></p>
<p> <%= link_to panel_show_users_path do %> <i class="fa fa-user fa-fw"></i> USERS</a> <% end %> </p>
<p> <%= link_to sign_out_path, method: :delete do %> <i class="fa fa-sign-out fa-fw"></i>  SIGN OUT</a> <% end %> </p>
<p>&nbsp;</p>

<span class="hidden-xs"><div class="controlsidebarhidden">
<p>&nbsp;</p>
</div></span>
</div>

app/views/panels/_story.erb
<tr>
	<td> <%= story.title %> </td>
	<td> <%= story.created_at %> </td>
	<td> <%= story.decorate_state %> </td>
	<td> <%= link_to "#{story.user.user_name} - #{story.user.list_roles}", user_path(story.user) %> </td>
	<td>
		
		<%= button_to 'Edit', edit_story_path(story), class: 'btn btn-success btn-xs', method: :get %>
		<%= button_to 'Delete', story_path(story), class: 'btn btn-danger btn-xs', method: :delete, confirm: "Are you sure you want to delete the story, '#{story.title}'? It will be permanantly delted!" %> 
		 
	</td>

</tr>

app/views/panels/_story.html.erb
<tr>
	<td> <%= story.title %> </td>
	<td> <%= story.created_at %> </td>
	<td> <%= story.decorate_state %> </td>
	<td> <%= link_to "#{story.user.user_name} - #{story.user.list_roles}", user_path(story.user) %> </td>
	<td>
		
		<%= button_to 'Edit', edit_story_path(story), class: 'btn btn-success btn-xs', method: :get %>
		<%= button_to 'Delete', story_path(story), class: 'btn btn-danger btn-xs', method: :delete, confirm: "Are you sure you want to delete the story, '#{story.title}'? It will be permanantly delted!" %> 
		 
	</td>

</tr>

app/views/panels/edit_event.html.erb
<%= render partial: 'sidebar' %> 
<div class="container">
	<div class="col-sm-9">
		<h2>Add a Calendar Event</h2>
		<form role="form">
		  	<div class="form-group">
			    <label for="Nameofevent">Name of Event</label>
			    <input type="text" class="form-control" id="NameofEvent" placeholder="Enter name of event">
			    <p>&nbsp;<p>
			    <label for="Descriptionofevent">Description</label>
			    <textarea class="form-control" rows="3"></textarea>
		    	<p>&nbsp;<p>

		    	<div class="col-sm-9">

			       <div class='col-sm-6'>
			        	<span class="bold">Start Date/Time   </span>
			            <div class="form-group">
			                <div class='input-group date' id='datetimepicker8'>
			 					<input type='text' class="form-control" />
			                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
			                </div>
			            </div>
			        </div>

			        <div class='col-sm-6'>
			            <span class="bold">Finish Date/Time   </span>
			            <div class="form-group">
			                <div class='input-group date' id='datetimepicker9'>
			                    <input type='text' class="form-control" />
			                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
			                </div>
			            </div>
			        </div>
			    </div> 

			    <div class = "clearfix"></div>

			    <script type="text/javascript">
			        $(function () {
			            
			            $('#datetimepicker8').datetimepicker();
			            $('#datetimepicker9').datetimepicker();
			            
			            $("#datetimepicker8").on("dp.change",function (e) {
			               $('#datetimepicker9').data("DateTimePicker").setMinDate(e.date);
			            });
			            $("#datetimepicker9").on("dp.change",function (e) {
			               $('#datetimepicker8').data("DateTimePicker").setMaxDate(e.date);
			            });
						
			        });
			    </script>

				<span class="bold">Choose Calendar to add this Event to</span>

			    <div class="radio">
  					<label>
    				<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
   					Public Calendar
  					</label>
				</div>
				<div class="radio">
  					<label>
    					<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
    					Admin Calendar
  					</label>
				</div>
				<div class="radio">
  					<label>
    					<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
    					Rider Calendar
  					</label>
				</div>
				<div class="radio">
  					<label>
    					<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
    					Midweek Calendar
  					</label>
				</div>
				<div class="radio">
  					<label>
    					<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
    					Coordinator Calendar
  					</label>
				</div>


				
		    	<p>&nbsp;<p>
 
				<button type="button" class="btn btn-success"><i class="fa fa-thumb-tack"></i> Add Event to this Calendar</button>
	    	</div>
                    
		</form>
              <p>&nbsp;<p>  
         <table class="table">
	<thead>
		<tr>
				<td><strong>DATE</strong></td>
				<td><strong>EVENT</strong></td>
		</tr>
		</thead>
		<tbody><tr>
				<td>06/07/2014 11:14 PM</td>
				<td>Annual Gen. Meeting of blood bikes wales</td>
				<td><button type="button" class="btn btn-success"> Edit</button>
                    <button type="button" class="btn btn-danger"> Delete</button></td>
            
		</tr>
		<tr>
				<td>NHS</td>
				<td>Andy Walters</td>
				<td><span class="hidden-xs"><a href="mailto:nhsliaison@bloodbikeswales.org.uk">nhsliaison@bloodbikeswales.org.uk</a></span></td>
				<td><a href="mailto:nhsliaison@bloodbikeswales.org.uk"><button type="publish" class="btn btn-success btn-xs">Email</button></a></td>

		</tr>
		<tr>
				<td>Secretary</td>
				<td>Pete Oxley</td>
				<td><span class="hidden-xs"><a href="mailto:secretary@bloodbikeswales.org.uk">secretary@bloodbikeswales.org.uk</a></span></td>
				<td><a href="mailto:secretary@bloodbikeswales.org.uk"><button type="publish" class="btn btn-success btn-xs">Email</button></a></td>

		</tr>

</tbody></table>       
                
                
	</div>
</div>

app/views/panels/edit_story.html.erb
<%= render partial: 'panels/sidebar' %> 




<div class="col-sm-10">
	<h2>Edit News Story</h2>

<div class="col-sm-10">
	<h2>News</h2>
	<h4>EDIT STORY</h4>
							
				


<%= form_for( @story ) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
  	<%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: @story.title %><br>
    
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: @story.description, rows: 4 %>

    <%= f.label :image %><br>
    <%= show_uploaded_image(@story.photo, width: 800, height: 504, for: :story) %><br>
    <div class = 'clearfix'></div>
    <%= f.file_field :file_name %>

  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Publish', class: 'btn btn-success' %>
    <p></p>
    
  </div>
<% end %>
<%= button_to 'Delete', story_path(@story), class: 'btn btn-danger', method: :delete, confirm: "Are you sure you want to delete the story, '#{@story.title}'? It will be permanantly delted!" %> 




<p>&nbsp;</p>

</div>

						
</div>

app/views/panels/media.html.erb
<%= render partial: 'panels/sidebar' %> 




<div class="col-sm-10">
	<h2>Media</h2>


 

  <%= render partial: 'page', collection: @pages %>


						
</div>

app/views/panels/media_edit.html.erb
<%#= debug @field %>
<h2> Editing <%= @field.name %> </h2>
<!-- panel_update_media -->



<%= form_for( @field, url: panel_update_media_path(@field) ) do |f| %>
	<%= f.text_area :content, class: 'form-control', rows: 20 %>
	<br>
	<%= f.submit class: 'form-control btn btn-success' %>
<% end %>

app/views/panels/pages.html.erb
<%= render partial: 'panels/sidebar' %> 




<div class="col-sm-10">
	<h2>Edit Pages</h2>


 

  <%= render partial: 'page', collection: @pages %>


						
</div>

app/views/panels/stories.html.erb
<%= render partial: 'sidebar' %> 

<div class="col-sm-10">
				<h2>Edit News Story</h2>
							
<table class="table">
	<thead>		
		<tr>
			<td><strong>TITLE</strong></td>
			<td><strong>DATE RECIEVED</strong></td>
			<td><strong>PUBLISHED</strong></td>
			<td><strong>AUTHOR</strong></td>
			<td>&nbsp;</td>
		</tr>
	</thead>
<tbody>
	<%#= will_paginate @stories %>

	<%= render partial: 'story', collection: @stories %>

</tbody>
</table>


</div>

app/views/panels/users.html.erb
<%= render partial: 'sidebar' %> 


<div class="col-sm-10">
<%= will_paginate @users %>

				<h2>Users</h2>
<div class="table-responsive">						
<table class="table">
	<thead>		
			<tr>
				<td> User Name</td>
				<td> Applied </td>
				<td> Accepted </td>
				<td> Roles </td>
				<td> Posts </td>
				<td> Discussions Started </td>
				<td> Email </td>
				<td> Public Email </td>
				<td> Landline </td>
				<td> Mobile </td>
				<td> Address </td>
				<td> Postcode </td>

			</tr>
	</thead>
	

	<tbody>
		<% @users.each do |user| %>
			<tr class = <%= if user.is_admin? 
			  	"success"
				  elsif user.is_coordinator? || user.is_midweek? || user.is_rider? && !user.is_admin?	  	
				  elsif user.is_only_potential?
				  	"danger"
				  end
			%>>
					<td> <%= link_to user.user_name, user_path(user) %> </td>
					<td> <%= user.created_at.strftime('%a, %b %d, %Y %I:%M%P') %> </td>
					<td> <% if user.accepted_at %>
							<%= user.accepted_at.strftime('%a, %b %d, %Y %I:%M%P') %>
						  <% else %> 
						  	TBA
						  <% end %> </td>



					<td>

						<%= form_for user, url: panel_update_user_path(user) do |f| %>

							<% if user.is_admin? %>
								<i class = "fa fa-check-square"></i>
							<% else %>
								<i class = "fa fa-square"></i>
							<% end %>
							
							Admin

							<%= f.check_box :coordinator %>
							Coordinator 

							<%= f.check_box :midweek %>
							Midweek

							
							<%= f.check_box :rider %>
							Rider





					</td>
					
					<td> <%#= user.posts.count %> </td>
					<td> <%#= user.discourses.count %> </td>
					<td> <%= user.email %></td>
					<td> <%= user.public_email %></td>

	
					<td> <%= user.landline %> </td>
					<td> <%= user.mobile %> </td>

					<td> <%= user.address %> </td>
					<td> <%= user.postcode %> </td>

					<td> 

						<%= f.submit 'Approve', class: 'btn btn-success btn-xs fleft', method: :patch %>

					<% end %>

						<%= button_to 'Delete', delete_user_path(user), class: 'btn btn-danger btn-xs', method: :delete, confirm: 'Are you sure you want to delete ' + user.user_name + '? They currently have these roles: ' + user.list_roles %>



					</td>	
				</tr>	
			<tr>

		<% end %>

				
		
	</tbody>
</table>
</div>




<p>&nbsp;</p>

</div>
</div>