config/routes.rb
Bloodbikeswales::Application.routes.draw do
# splash pages
  root 'splash#index'

  get 'about', to: 'splash#about', as: :splash_about
  get 'news', to: 'stories#index', as: :splash_news
  get 'events', to: 'splash#events', as: :splash_events
  get 'sponsors', to: 'splash#sponsors', as: :splash_sponsors
  get 'contact_list', to: 'splash#contact', as: :splash_contact
  get 'links', to: 'splash#links', as: :splash_links
  get 'fundraising', to: 'splash#fundraising', as: :splash_fundraising

  post 'user/:user_id/avatar', to: 'images#create', as: :user_avatar_create
#  post 'story/:story_id/image', to: 'images#story_create', as: :story_image_create


  resources :users, except: :index do
    resources :notifications, only: :index
  end

  resources :recitals
  resources :events
  resources :images

  resources :forums do
    resources :discussions do
      member do
        get 'followers', to: 'discussions#show_followers', as: :show_followers
        get 'create_follower', to: 'discussions#create_follower', as: :create_follower
        get 'delete_follower', to: 'discussions#delete_follower', as: :delete_follower
      end

      resources :replies
    end
  end

  resources :stories, except: [:edit]

  scope path: 'control_panel' do
      get 'pages', to: 'panels#pages', as: :panel_show_pages
      get 'pages/:id', to: 'panels#pages', as: :panel_edit_pages

      get 'edit_story/:id', to: 'stories#edit', as: :edit_story
      get 'stories', to: 'panels#stories', as: :panel_show_stories

      get 'users', to: 'panels#users', as: :panel_show_users
      delete 'user/:id', to: 'panels#user_delete', as: :delete_user
      patch 'user/:id', to: 'panels#user_update', as: :panel_update_user

      get 'media', to: 'panels#media', as: :panel_show_media

      get 'edit_media/:id', to: 'panels#media_edit', as: :panel_edit_media
      delete 'media/:id', to: 'panels#media_delete', as: :panel_delete_media
      patch 'media/:id', to: 'panels#media_update', as: :panel_update_media

      get 'events/:id', to: 'panels#edit_event', as: :panel_edit_event
    #  delete 'events/:id'
      
    resources :stories
  end

#  resources :stories

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user

#  get 'panels/stories', to: 'panels#stories', as: :panel_show_stories
 # delete 'panels/story/:id', to: 'panels#story_delete', as: :delete_story
 # patch 'panels/story/:id', to: 'panels#story_update', as: :panel_update_story

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user


  # use a member route here
  post 'create', to: 'create_reply/:forum_id/:discourse_id', to: 'replies#create'
  post 'create_retort/:forum_id/:discourse_id/:reply_id', to: 'retorts#create', as: :create_reply_retort

  private_dir = 'private'
  get "#{private_dir}/:file_name.:extension", to: 'images#show', as: :private_image

  get 'members_contact_list', to: 'contact_lists#show'

  get 'send_registration_email/:id', to: 'users#send_registration_email', as: :send_registration_email
  get 'culminate/:register_key', to: 'users#culminate', as: :culminate

  get 'signup', to: 'users#new', as: 'sign_up'
  get 'signin', to: 'sessions#new', as: 'sign_in'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'signout', to: 'sessions#destroy', as: 'sign_out'
end

app/models/user.rb
class User < ActiveRecord::Base
	after_create :send_tracy_email

	def send_tracy_email
		Notification.new_user_notification(self).deliver
	end

	include SoftDelete

	has_many :posts
	has_many :discussions

	has_many :followers
	has_many :discussions, -> { uniq }, through: :followers

	has_one :avatar, class_name: 'Image', foreign_key: :user_id

	has_many :replies
	has_many :retorts

	has_many :stories

	has_many :user_roles
	has_many :roles, through: :user_roles

	before_save { self.email = email.downcase }

	before_create :create_register_token
	before_create { self.culminated = 0 } #setting to false results in strange error where it can't be saved
	before_create :create_remember_token
	before_create { self.user_roles.build(role_id: Role.find_by(role: 'potential').id ) } # user the add_role method here

	before_destroy { save_name_to_all_authored_discussions 
					 save_name_to_all_authored_replies }


	state_machine initial: :unregistered do 

		event :register do
			transition unregistered: :registered 
		end

		event :unregister do
			transition registered: :unregistered
		end

	end

	def save_name_to_all_authored_discussions
		self.discussions.each do |discussion|
			ap discussion
			discussion.update_attributes(author_name: user_name)
		end
	end

	def save_name_to_all_authored_replies
		self.replies.each do |reply|
			reply.update_attributes(author_name: user_name)
		end
	end


	def send_register_email
		UserMailer.registration(self).deliver
	end

	def soft_delete_message
		'widget' + self.first_name
	end

	def return_deleted_at
		self.soft_deleted_at
	end

	VALID_EMAIL_REGEX = /[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9\-.]/

	validates :first_name,
			  presence: true, 
			  if: :first_name


	validates :last_name,
			  presence: true,
			  if: :last_name


	validates :user_name,
			  presence: true,
			  uniqueness: true,
			  if: :user_name


	validates :email, presence: true, 
					  uniqueness: { case_sensitive: false },
					  format: { with: VALID_EMAIL_REGEX }, 
					  if: :email 


	validates :password,
			  length: { minimum: 6, maximum: 10 },
			  if: :password
	





	has_secure_password



	def role_array
		self.roles.pluck(:role)
	end

	def has_role?(role)
		role_array.include?(role)
	end

	def allowed_forums
		allowed = []

		Forum.all.each do |forum|
			allowed << forum if forum.user_allowed?(self)
		end

		allowed
	end

	def most_popular_discussion




		most_popular = allowed_forums.first.discourses.first


		allowed_forums.each do |forum|



			forum.discourses.each do |discourse|


				most_popular = discourse if discourse.impression_count > most_popular.impression_count

			end

		end

		most_popular



	end

	def is_admin?
		role_array.include?('admin')
	end

	def is_coordinator?
		role_array.include?('coordinator')
	end

	def is_midweek?
		role_array.include?('midweek')
	end

	def is_rider?
		role_array.include?('rider')
	end

	def is_only_potential?
		if role_array === ['potential'] 
			true
		else
			false
		end
	end


	# virtual attributes
	def admin
		is_admin?
	end

	def coordinator
		is_coordinator?
	end

	def midweek
		is_midweek?
	end

	def rider
		is_rider?
	end
	


	def make_admin!
		add_role('admin')
	end

	def make_coordinator!
		add_role('coordinator')
	end

	def make_midweek!
		add_role('midweek')
	end

	def make_rider!
		add_role('rider')
	end



	def denounce_admin!
		remove_role('admin')
	end

	def denounce_coordinator!
		remove_role('coordinator')
	end

	def denounce_midweek!
		remove_role('midweek')
	end

	def denounce_rider!
		remove_role('rider')
	end


	def as
		
	end





	def is_op?
		#? :
	end


	def is_current_user?
		if current_user === self
			true
		else
			false
		end
	end

	def is_admin?
		if self.roles.pluck(:role).include?('admin')
			true 
		else 
			false
		end
	end




	def add_role(role)

#		ap 'Adding role ' + role

		self.update_attributes(accepted_at: Time.now) if self.is_only_potential?	

		self.user_roles.create(role_id: Role.find_by(role: role).id ) if !self.has_role?(role)


	end

	def remove_role(role)

#		ap 'Removing role ' + role

#		self.update_attribute(revoked_at: Time.now) if self.is_only_potential?	

		self.user_roles.find_by( role_id: Role.find_by(role: role).id ).destroy if self.has_role?(role)
	end

	def list_roles
		self.roles.pluck(:role).to_sentence
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private 

		def create_register_token
			self.register_key = User.hash(User.new_remember_token)
			self.register_token_created_at = Time.now
		end

		def create_remember_token
			self.register_key = User.hash(User.new_remember_token)
	#		update_attribute(:remember_token, 'hiya boyz')
		end

=begin
		Do this in future. Make the register key more secure with a hash
		def create_register_key

		end


		def culminate
			update_attribute(:culminated, 1)
		end
=end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :send_registration_email]

  before_action :secure, only: [:edit, :update, :destroy, :send_registration_email]

  before_action :no_current_user, only: [:new, :create]
 # before_action :set_up_negative_captcha, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    ap @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    roles = Role.all
    
    @role_names = []

    roles.each do |role|
      @role_names << role.role
    end

  end

  def culminate

    @user = User.find_by(register_key: params[:register_key])

    if @user.registered?
      redirect_to @user, notice: "This user has already confirmed their acount."
    else
      @user.register
      redirect_to @user, notice: "Thanks for confirming this user's email address !"
    end
  
  end

  def send_registration_email
    @user.send_register_email

    redirect_to @user, notice: "Email sent to #{@user.email}. If this is the wrong email, #{view_context.link_to 'click here to change your details!', edit_user_path(@user)}".html_safe
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|

#      if simple_captcha_valid?
        if @user.save
        
          sign_in @user
          @user.send_register_email

          
          format.html { redirect_to @user , notice: 'Welcome to ' + request.host_with_port + ', ' + @user.user_name + '!' }
          format.json { render action: 'show', status: :created, location: @user }
        else


          flash_message = 'We could not create your account. Please try again!'
          
#          flash_message << ' The recaptcha was wronge!' unless simple_captcha_valid?
          
          flash.now[:notice] = flash_message
          format.html { render action: 'new' }
  #        format.json { render json: @user.errors, status: :unprocessable_entity }
        end
 #     end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

#    ap params

    
#    user_params.delete_blanks!



#    @image = @user.create_avatar(file_name: user_params[:avatar][:file_name])
 

    respond_to do |format|
      #.delete avatar: [:file_name]

      if @user.update_attributes(user_params) # this automatically deletes any avatar instances, as uploaded files are saved in a seperate model
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def permitted_attributes
     [:user_name,
      :email,
      :first_name,
      :last_name,
      :nearest_town,
      :postcode,
      :user_name,
      :password,
      :password_confirmation,
      :address,
      :public_email,
      :landline,
      :mobile]
    end

    def no_current_user
      redirect_to root_url if current_user 
    end

    def secure
      redirect_to root_url unless current_user === @user || current_user.is_admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id]).decorate

    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      ap params
      # "first_name", "last_name", "nearest_town"]
      # ["id", "user_name", "email", "password_digest", "created_at", "updated_at", "register_key", "culminated", "remember_token", "register_token_created_at", "profile_image", "licence_image", "first_name", "last_name", "nearest_town"] 

      # avatar: [:file_name]
     params.require(:user).permit(permitted_attributes)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def name_or_email(user)
	
	end

	def	contextual_user(user)
		if user === current_user
			'Your'		
		else
			user.user_name + '\'s'
		end
	end

end

app/views/users/_form.html.erb
<%= form_for(@user, html: { multipart: true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div>

  </div>

  <div class="field">
    <!--
    Current Roles: <br>
    Add Roles: <br>

    <%#= f.label :roles %><br>
    <%#= f.select :roles, @role_names   %>
    -->
  </div>





  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_image_upload.erb
  <%= show_uploaded_image(@user.avatar, width: 100, height: 100) %>

  <% if !@user.is_only_potential? %>
    <% if current_user == @user || current_user.is_admin? %> 
        <h4> Upload new profile image: </h4>
        
        <%= form_for(@user, :html => { :multipart => true }, url: user_avatar_create_path(@user), method: :post ) do |f| %>
                <%= f.file_field :file_name %>
                <br>
                <%= f.submit 'Upload Image' %>
                <br>
                <p class="help-block">Please make sure your image is a jpeg and no bigger than 2MB</p>
          <% end %>    

      <% end %>
  <% end %>

app/views/users/_private_info.html.erb
  <p><strong> <%= 'Role'.pluralize(@user.roles.count) %>:</strong>  <%= @user.list_roles %> </p>

  <div class = 'clearfix'></div>
  <% if current_user == @user || current_user.is_admin? %> 

  <h3> Private Info: </h3> <h4> - Only <%= @user.contextual_custom( admin_message: "#{@user.user_name} and admins", owner_message: 'yourself and select admins', visitor_message: "#{@user.user_name} and admins", guest_messaeg: "#{@user.user_name} and admins") %> can view this information </h4>
  
  <p><strong>First Name:</strong> <%= @user.decorate_first_name %> </p>
  <p><strong>Last Name:</strong>  <%= @user.decorate_last_name %></p>
  <p><strong>Email:</strong> <%= @user.decorate_email %> </p>

  <p><strong>Address:</strong> <%= @user.decorate_address %> </p>
  <p><strong>Landline:</strong> <%= @user.decorate_landline %> </p>
  <p><strong>Mobile:</strong> <%= @user.decorate_mobile %> </p>

  <p><strong>Nearest Town:</strong>  <%= @user.decorate_nearest_town %></p>
  <p><strong>Post Code:</strong>  <%= @user.decorate_post_code %></p>

  <p>&nbsp;</p>

    
    <% if @user === current_user %>
      <%= button_to 'Edit Your Details', edit_user_path, class: 'btn btn-success', method: :get %>
    <% elsif %>
      <%= button_to 'Edit ' + @user.user_name + '\'s Details', edit_user_path, class: 'btn btn-success', method: :get %>    
    <% end %>

  <% end %>

app/views/users/edit.html.erb
<div class="container">
<p>&nbsp;</p>

<div class="row">
<div class="col-md-12">


<h2>Edit Your Profile</h2>

				
				
<%= form_for(@user) do |f| %>


  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
     
    </div>
  <% end %>

  <%= f.label 'User Name' %><br>
  <%= f.text_field :first_name, class: 'form-control' %><br>

  <%= f.label 'First Name' %><br>
  <%= f.text_field :first_name, class: 'form-control' %><br>

  <%= f.label 'Last Name' %><br>
  <%= f.text_field :last_name, class: 'form-control' %><br>

  <%= f.label 'Public Email' %><br>
  <%= f.email_field :public_email, class: 'form-control' %><br>

  <%= f.label 'Email' %><br>
  <%= f.email_field :email, class: 'form-control' %><br>

  <%= f.label 'Address' %><br>
  <%= f.text_field :address, class: 'form-control' %><br>

  <%= f.label 'Nearest Town' %><br>
  <%= f.text_field :nearest_town, class: 'form-control' %><br>

  <%= f.label 'Landline' %><br>
  <%= f.text_field :landline, class: 'form-control' %><br>

  <%= f.label 'Mobile' %><br>
  <%= f.text_field :mobile, class: 'form-control' %><br>


  <%= f.label 'Postcode' %><br>
  <%= f.text_field :postcode, class: 'form-control' %><br>

  <%= f.submit 'Update', class: 'btn btn-success' %><br>
  
<% end %>
				

<div class="col-md-12">
			


  <div class="clearfix"></div>
</div>
<div class="col-md-12">


  <% if !@user.is_only_potential? %>

    <!-- make a partial -->
    <%= render 'image_upload' %>
  <!-- partial end-->

  <% end %>  


<p>&nbsp;</p>
<p><a href="#"><i class="fa fa-long-arrow-left"></i> Back to Blood Bikes Wales</a></p>

&nbsp;&nbsp;
<p>&nbsp;</p>
		
</div>
</div>
</div>

app/views/users/index.html.erb
<% page_title('All users') %>

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Email</th>


      <th> Roles </th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>

          <td>

            <% user.roles.each do |role| %>
              <%= role.role %>
            <% end %>

          </td>

        <td></td>
        <td></td>

        <td> <% %> </td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% page_title('Sign up') %>


<div class="row">
<div class="col-md-12">

				<h2>Register</h2>
							<p>We are always looking for volunteers. All you have to do is fill in the contact form below and we'll contact you as soon as we can.</p>
							<p>Remember - how much, or how little, you do for Blood Bikes Wales is up to you, but you can be sure that whatever you do, you will be benefitting the health and wellbeing of patients and relatives as well as releasing funds back to the NHS for use in other areas.</p>
							<h5>Remember: You don't need to be a biker to join	Blood Bikes Wales.	All Volunteers Are Welcome</h5>

				


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%#= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %><br>

    <%= f.text_field(:first_name, class: 'form-control', placeholder: 'First Name') %> <br>
    <%= f.text_field(:last_name, class: 'form-control', placeholder: 'Last Name') %> <br>
    <%= f.text_field(:user_name, class: 'form-control', placeholder: 'User Name') %> <br>
    <%= f.text_field(:email, class: 'form-control', placeholder: 'Email') %> <br>
    <%= f.password_field(:password, class: 'form-control', placeholder: 'Create Password (must contain at least 8 characters)') %> <br>
    <%= f.password_field(:password_confirmation, class: 'form-control', placeholder: 'Confirm Password') %> <br>
    <%= f.text_field(:nearest_town, class: 'form-control', placeholder: 'Your Nearest Town') %> <br>
    <%#= show_simple_captcha %>
    

    <%= f.submit 'Create my Account', class: 'btn btn-success', method: 'get' %>

<% end %>
<br>

<%= link_to root_path do %>
 <i class="fa fa-long-arrow-left"></i> Back to Blood Bikes Wales
<% end %>


</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-12">
		

	<h2> <%= @user.contextual_owner('Your') %> Profile </h2>


	
  <!-- make a partial -->
  <%= render 'image_upload' %>
  <!-- partial end-->


  <h3> Public Info: </h3>
  

  <p><strong>User Name:</strong>  <%= @user.decorate_user_name %></p>
  <p><strong>Public Email:</strong>  <%= @user.decorate_public_email %></p>
  <p><strong>Registration State:</strong>  <%= @user.decorate_state %></p>

<!--
  <p><strong>Number of Discussions:</strong>  <%#= @user.decorate_discussion_count %> </p>

  <p><strong>Number of Replies:</strong> <%#= @user.decorate_replies_count %>  </p>
--> 

	<div class = 'clearfix'></div>
	<%#= image_tag .file_name, class: 'mugshot', width: 200 %>

<%= @user.decorate_private_info %>


</div>
<div class="col-md-12">			
  <div class="clearfix"></div>
</div>
<div class="col-md-12">




<%#= form_for(@user, :html => { :multipart => true }) do |f| %>
   <div class="field">
     <%#= f.label :message %><br>
     <%#= f.text_field :message %>
   </div>

   <%#= f.fields_for :post_attachment do |p| %>
     <div class="field">
       <%#= p.label :avatar %><br>
       <%#= p.file_field :avatar %>
     </div>
   <%# end %>

   <div class="actions">
     <%#= f.submit %>
   </div>
<%# end %>



<p>&nbsp;</p>




  


<%= link_to user_path(@user) do %>
	<i class="fa fa-long-arrow-left"></i> Back to Blood Bikes Wales
<% end %>

		
</div>
</div>