config/routes.rb
Bloodbikeswales::Application.routes.draw do
# splash pages
  root 'splash#index'

  get 'about', to: 'splash#about', as: :splash_about
  get 'news', to: 'stories#index', as: :splash_news
  get 'events', to: 'splash#events', as: :splash_events
  get 'sponsors', to: 'splash#sponsors', as: :splash_sponsors
  get 'contact_list', to: 'splash#contact', as: :splash_contact
  get 'links', to: 'splash#links', as: :splash_links
  get 'fundraising', to: 'splash#fundraising', as: :splash_fundraising

  post 'user/:user_id/avatar', to: 'images#create', as: :user_avatar_create
#  post 'story/:story_id/image', to: 'images#story_create', as: :story_image_create


  resources :users, except: :index do
    resources :notifications, only: :index
  end

  resources :recitals
  resources :events
  resources :images

  resources :forums do
    resources :discussions do
      member do
        get 'followers', to: 'discussions#show_followers', as: :show_followers
        get 'create_follower', to: 'discussions#create_follower', as: :create_follower
        get 'delete_follower', to: 'discussions#delete_follower', as: :delete_follower
      end

      resources :replies
    end
  end

  resources :stories, except: [:edit]

  scope path: 'control_panel' do
      get 'pages', to: 'panels#pages', as: :panel_show_pages
      get 'pages/:id', to: 'panels#pages', as: :panel_edit_pages

      get 'edit_story/:id', to: 'stories#edit', as: :edit_story
      get 'stories', to: 'panels#stories', as: :panel_show_stories

      get 'users', to: 'panels#users', as: :panel_show_users
      delete 'user/:id', to: 'panels#user_delete', as: :delete_user
      patch 'user/:id', to: 'panels#user_update', as: :panel_update_user

      get 'media', to: 'panels#media', as: :panel_show_media

      get 'edit_media/:id', to: 'panels#media_edit', as: :panel_edit_media
      delete 'media/:id', to: 'panels#media_delete', as: :panel_delete_media
      patch 'media/:id', to: 'panels#media_update', as: :panel_update_media

      get 'events/:id', to: 'panels#edit_event', as: :panel_edit_event
    #  delete 'events/:id'
      
    resources :stories
  end

#  resources :stories

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user

#  get 'panels/stories', to: 'panels#stories', as: :panel_show_stories
 # delete 'panels/story/:id', to: 'panels#story_delete', as: :delete_story
 # patch 'panels/story/:id', to: 'panels#story_update', as: :panel_update_story

#  get 'panels/users', to: 'panels#users', as: :panel_show_users
#  delete 'panels/user/:id', to: 'panels#user_delete', as: :delete_user
#  patch 'panels/user/:id', to: 'panels#user_update', as: :panel_update_user


  # use a member route here
  post 'create', to: 'create_reply/:forum_id/:discourse_id', to: 'replies#create'
  post 'create_retort/:forum_id/:discourse_id/:reply_id', to: 'retorts#create', as: :create_reply_retort

  private_dir = 'private'
  get "#{private_dir}/:file_name.:extension", to: 'images#show', as: :private_image

  get 'members_contact_list', to: 'contact_lists#show'

  get 'send_registration_email/:id', to: 'users#send_registration_email', as: :send_registration_email
  get 'culminate/:register_key', to: 'users#culminate', as: :culminate

  get 'signup', to: 'users#new', as: 'sign_up'
  get 'signin', to: 'sessions#new', as: 'sign_in'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'signout', to: 'sessions#destroy', as: 'sign_out'
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user

	has_one :photo, class_name: 'Image', foreign_key: :story_id

	validates :title, presence: true
	validates :description, presence: true		





#	scope :recent, order('events.created_at ASC').limit(8)


	scope :recent, -> { order('stories.approve_date DESC').limit(5) }
	scope :approved, -> { where( state: 'approved') }#{ state: 'approved' }

	 
	scope :disapproved, -> { where( state: 'disapproved') }

	state_machine initial: :disapproved do
		after_transition on: :approve, do: :set_approve_date
		after_transition on: :disapprove, do: :clear_approve_date

		event :approve do
			transition disapproved: :approved
		end		

		event :disapprove do
			transition approved: :disapproved
		end
	end

	private
		def clear_approve_date
			self.update_attributes(approve_date: nil)
		end

		def set_approve_date
			self.update_attributes(approve_date: DateTime.now)
		end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :only_non_potentials, only: [:new, :create]

  before_action :only_admins, only: [:edit, :update]
  before_action :set_story, only: [:show, :destroy, :edit, :update]
  
#  before_action :_story, only: [:edit]
  def index
    @stories = Story.approved.paginate(page: params[:page], per_page: 10)
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

 
  def create
    new_params = story_params.except("file_name")

    @story = Story.new(story_params)
    @story.user_id = current_user.id

    if story_params[:file_name]
      @story.create_photo(file_name: story_params[:file_name] ) 
    end

    if @story.save
      redirect_to root_path, notice: "Thanks! Your story, '#{@story.title}' has been submitted and may be published by an administrator!"
    else
      render 'new', notice: 'Sorry! Your story could not be published!'
    end
  end

  def destroy
    @story.destroy
 
    redirect_to panel_show_stories_path, notice: "Successfully deleted #{@story.title} "
  end

  def edit
    render template: 'panels/edit_story'
  end

  def update




#    new_params = story_params.except("file_name")

    if story_params[:file_name]
      @story.create_photo(file_name: story_params[:file_name] ) 
    end


    if @story.update(story_params)
      @story.approve
      redirect_to splash_news_path, notice: "Successfully updated #{@story.title} " 
    else
    end
  end

#  def update
#  end

  private
    def only_admins
      redirect_to root_path unless current_user.is_admin?
    end

    def set_story
      @story = Story.find(params[:id])
    end

    def only_non_potentials
      redirect_to(root_path, notice: 'Sorry, only trusted users can enter stories!') if current_user.is_only_potential?
    end

    def protect_admin
      redirect_to(panel_show_users_url, notice: 'You lack the privileges needed to alter an admin') if @user.is_admin? 
    end

    def set_all_users
     @users = User.all.paginate(page: params[:page], per_page: 10)
    end

    def story_params
      params.require(:story).permit(:title, :description, :file_name)
    end

    def secure
      redirect_to root_url if !current_user.is_admin?
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params

     params.require(:user).permit(:coordinator, :midweek, :rider)
    end
end

app/views/stories/_form.html.erb
<%= form_for( @story, html: { multipart: true } ) do |f| %>

  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this discourse from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">



    <%= f.text_field :title, placeholder: 'Create your story\'s title here' , class: 'form-control' %><br>
    <%= f.text_area :description, placeholder: 'Write your story here! Make sure it\'s no longer than 400 characters!', class: 'form-control', rows: 5 %><br>

          <h4> Upload new story pic: </h4>
          
    <%= f.file_field :file_name %>
          <%#= form_for( url: story_image_create_path(@story), method: :post ) do |f| %>
                  <%#= f.file_field :file_name %>
                  <%#= f.submit 'Upload Image' %>
            <!--      <p class="help-block">Please make sure your image is a jpeg and no bigger than 2MB</p>   -->
          <%# end %>    


  


  </div>

  <div class="actions">
    <%= f.submit 'Submit Story', class: 'form-control btn btn-success' %>
  </div>
<% end %>


  <%#= form_for [@forum, @discussion] do |f| %>

    <%#= f.text_field :name, class: 'form-control', placeholder: 'Create a new title here...' %><br>
    <%#= f.text_area :description, class: 'form-control', placeholder: 'Expand on your title here...', rows: 5 %><br>
    
    <%#= f.submit 'Create Discussion', class: 'form-control btn btn-primary' %>

  <%# end %>

app/views/stories/_story.html.erb
<div class="row">
 	
		<span class="hidden-xs">
			<div class="col-sm-3"> 
				<%= show_uploaded_image(story.photo, width: 800, height: 504, class: 'img-responsive newsthumbimage', for: :story ) %> 

			</div>
		</span>

		<div class="col-sm-8">

			<h4> <%= story.title %></h4>

			<p> <%= truncate story.description, length: 300 %></p>


			<%= link_to 'read more', story_path(story) %>

		</div>

</div>

app/views/stories/edit.html.erb
edit the storyyyyyy

app/views/stories/index.html.erb
<% find_fields(:news) %>

<div class="fullwidthcontainer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			</div>
		<div class="col-md-4">
			<h2><%= dynamic_content(:title) %></h2>
		</div>

		<%= will_paginate @stories %>

		</div>	
			<%= render partial: 'story', collection: @stories %>

	</div>		


</div>

app/views/stories/new.html.erb
<br>

<%= render partial: 'form' %>

<!--
<button id = 'insert'> insert character </button>
<button id = 'remove'> remove character </button>


<button id = 'insert_bold'> insert bold </button>
<button id = 'remove_bold'> remove bold </button>


<button id = 'insert_link'> insert link </button>
<button id = 'remove_link'> remove link </button>
-->

app/views/stories/show.html.erb
<div class="fullwidthcontainer">
		<div class="container">
				<div class="row">
					<div class="col-md-12">

						<h1> <%= @story.title %> </h1>
						<P><strong> <%= @story.user.user_name %> </strong> <%= @story.user.list_roles %> &#8226; <%= @story.created_at.strftime(' %d/%m/%Y') %></p>

						<%= show_uploaded_image @story.photo, width: 800, height: 504, class: 'img-responsive newsimage', for: :story %>
						
						<%= simple_format(@story.description) %>
						<%#= image_tag @story.photo.file_name, class: 'img-responsive newsimage' %>
					</div>
<p>&nbsp;</p>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4dcbdc1533c411d4"></script>
<!-- AddThis Button END -->

<%= link_to 'Back to all news', stories_path %> 

</div>
</div>
</div>


<p>&nbsp;</p>
</div>
<div class="row"></div>

</div>